name: "Static Analysis"

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 4.x
    paths:
      - '**.php'
      - '.github/workflows/phpstan.yml'
      - 'phpstan.neon.dist'
      - 'composer.json'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install Dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --error-format=github
